import { User, Job, Review, JobCategory, BudgetType, JobStatus, BadgeType } from '../types';

export const MOCK_REVIEWS: Review[] = [
    {
        id: 'r1',
        jobId: 'j2',
        reviewerId: 'u1',
        rating: 5,
        comment: 'Tom did an amazing job fixing my leaky faucet. He was quick, professional, and very friendly. Highly recommend!',
        date: '2 days ago',
    },
    {
        id: 'r2',
        jobId: 'j4',
        reviewerId: 'u3',
        rating: 4,
        comment: "Brenda was great with our dog, Skipper. She was on time and sent us a picture during the walk. Will hire again.",
        date: '1 week ago',
    },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Brenda P.',
    avatarUrl: 'https://i.pravatar.cc/150?u=u1',
    location: 'Hanover',
    bio: 'Community member looking to post and find jobs. Ready to help out!',
    skills: [JobCategory.LAWN_CARE, JobCategory.ERRANDS, JobCategory.PET_CARE],
    isVerified: true,
    memberSince: '2023',
    reviews: MOCK_REVIEWS.filter(r => r.reviewerId === 'u1'),
    badges: [BadgeType.ID_VERIFIED, BadgeType.FAST_RESPONDER],
  },
  {
    id: 'u2',
    name: 'Tom Wilson',
    avatarUrl: 'https://i.pravatar.cc/150?u=u2',
    location: 'Hanover',
    bio: 'Experienced handyman, specializing in small home repairs and garden work.',
    skills: [JobCategory.HANDYMAN, JobCategory.LAWN_CARE, JobCategory.SNOW_REMOVAL],
    isVerified: true,
    memberSince: '2022',
    reviews: MOCK_REVIEWS.filter(r => r.reviewerId !== 'u2'),
    badges: [BadgeType.ID_VERIFIED, BadgeType.COMMUNITY_PRO],
  },
  {
    id: 'u3',
    name: 'Sarah Jenkins',
    avatarUrl: 'https://i.pravatar.cc/150?u=u3',
    location: 'Walkerton',
    bio: 'I love helping people with organizing, cleaning, and errands. Let me help you!',
    skills: [JobCategory.CLEANING, JobCategory.ERRANDS],
    isVerified: false,
    memberSince: '2024',
    reviews: MOCK_REVIEWS.filter(r => r.reviewerId === 'u3'),
    badges: [],
  },
];

export const MOCK_JOBS: Job[] = [
    {
        id: 'j1',
        title: 'Mow my front and back lawn',
        description: 'Need someone to mow my lawn, about a quarter acre total. Should take about an hour. Please bring your own mower.',
        category: JobCategory.LAWN_CARE,
        location: 'Hanover',
        budget: { type: BudgetType.FIXED, amount: 40 },
        date: 'This Saturday afternoon',
        isUrgent: true,
        postedBy: 'u3',
        status: JobStatus.OPEN,
        applicants: ['u1', 'u2'],
    },
    {
        id: 'j2',
        title: 'Fix a leaky faucet in kitchen',
        description: 'My kitchen sink has been dripping for a week and it\'s driving me crazy. I have a replacement washer but I can\'t get the old one off.',
        category: JobCategory.HANDYMAN,
        location: 'Hanover',
        budget: { type: BudgetType.HOURLY, amount: 50 },
        date: 'Flexible',
        isUrgent: false,
        postedBy: 'u1',
        assignedTo: 'u2',
        status: JobStatus.COMPLETED,
        applicants: [],
    },
    {
        id: 'j3',
        title: 'Help moving a heavy couch',
        description: 'I bought a new couch and need help getting it up to my second-floor apartment. It\'s heavy, so definitely a two-person job.',
        category: JobCategory.MOVING,
        location: 'Durham',
        budget: { type: BudgetType.FIXED, amount: 75 },
        date: 'Tomorrow at 5pm',
        isUrgent: true,
        postedBy: 'u2',
        status: JobStatus.OPEN,
        applicants: [],
    },
    {
        id: 'j4',
        title: 'Walk my golden retriever',
        description: 'I have to go out of town unexpectedly and need someone to walk my dog, Skipper, twice a day for Wednesday and Thursday.',
        category: JobCategory.PET_CARE,
        location: 'Hanover',
        budget: { type: BudgetType.HOURLY, amount: 20 },
        date: 'This Wed & Thurs',
        isUrgent: false,
        postedBy: 'u3',
        assignedTo: 'u1',
        status: JobStatus.IN_PROGRESS,
        applicants: [],
    }
];